export interface Theme {
  name: string;
  primary: string;
  background: string;
  accent: string;
  text: string;
  font: string;
  rounded: string;
  buttonStyle: 'filled' | 'outline' | 'soft';
  gradient: boolean;
  gradientFrom?: string;
  gradientTo?: string;
  pattern?: 'dots' | 'waves' | 'none';
}

export const PRESET_THEMES: Record<string, Theme> = {
  minimal: {
    name: 'Minimal',
    primary: '#3B82F6',
    background: '#FFFFFF',
    accent: '#1F2937',
    text: '#111827',
    font: 'Inter',
    rounded: 'rounded-lg',
    buttonStyle: 'filled',
    gradient: false,
    pattern: 'none',
  },
  gradientSunset: {
    name: 'Gradient Sunset',
    primary: '#F97316',
    background: '#FFF7ED',
    accent: '#9333EA',
    text: '#78350F',
    font: 'Poppins',
    rounded: 'rounded-2xl',
    buttonStyle: 'soft',
    gradient: true,
    gradientFrom: '#F97316',
    gradientTo: '#9333EA',
    pattern: 'waves',
  },
  darkMode: {
    name: 'Dark Mode',
    primary: '#10B981',
    background: '#0F172A',
    accent: '#E4E4E7',
    text: '#F8FAFC',
    font: 'Inter',
    rounded: 'rounded-xl',
    buttonStyle: 'filled',
    gradient: false,
    pattern: 'dots',
  },
  coffeeShop: {
    name: 'Coffee Shop',
    primary: '#B45309',
    background: '#FEFCE8',
    accent: '#78350F',
    text: '#451A03',
    font: 'Merriweather',
    rounded: 'rounded-md',
    buttonStyle: 'outline',
    gradient: false,
    pattern: 'none',
  },
  barbiePink: {
    name: 'Barbie Pink',
    primary: '#EC4899',
    background: '#FCE7F3',
    accent: '#BE185D',
    text: '#831843',
    font: 'Quicksand',
    rounded: 'rounded-3xl',
    buttonStyle: 'soft',
    gradient: true,
    gradientFrom: '#EC4899',
    gradientTo: '#F472B6',
    pattern: 'none',
  },
  oceanVibes: {
    name: 'Ocean Vibes',
    primary: '#06B6D4',
    background: '#EFF6FF',
    accent: '#0F766E',
    text: '#164E63',
    font: 'Montserrat',
    rounded: 'rounded-xl',
    buttonStyle: 'filled',
    gradient: true,
    gradientFrom: '#06B6D4',
    gradientTo: '#0D9488',
    pattern: 'waves',
  },
  corporate: {
    name: 'Corporate Blue',
    primary: '#1E40AF',
    background: '#F9FAFB',
    accent: '#374151',
    text: '#111827',
    font: 'Roboto',
    rounded: 'rounded-md',
    buttonStyle: 'filled',
    gradient: false,
    pattern: 'none',
  },
  startup: {
    name: 'Startup Purple',
    primary: '#7C3AED',
    background: '#FFFFFF',
    accent: '#312E81',
    text: '#1F2937',
    font: 'Inter',
    rounded: 'rounded-2xl',
    buttonStyle: 'soft',
    gradient: true,
    gradientFrom: '#7C3AED',
    gradientTo: '#A78BFA',
    pattern: 'dots',
  },
  fitness: {
    name: 'Fitness Energy',
    primary: '#EF4444',
    background: '#FEF2F2',
    accent: '#991B1B',
    text: '#7F1D1D',
    font: 'Oswald',
    rounded: 'rounded-lg',
    buttonStyle: 'filled',
    gradient: true,
    gradientFrom: '#EF4444',
    gradientTo: '#F97316',
    pattern: 'none',
  },
  education: {
    name: 'Education',
    primary: '#2563EB',
    background: '#FFFFFF',
    accent: '#1E3A8A',
    text: '#1E40AF',
    font: 'Lato',
    rounded: 'rounded-lg',
    buttonStyle: 'outline',
    gradient: false,
    pattern: 'none',
  },
  nature: {
    name: 'Nature Green',
    primary: '#16A34A',
    background: '#F0FDF4',
    accent: '#166534',
    text: '#14532D',
    font: 'Nunito',
    rounded: 'rounded-xl',
    buttonStyle: 'soft',
    gradient: true,
    gradientFrom: '#16A34A',
    gradientTo: '#84CC16',
    pattern: 'waves',
  },
  luxury: {
    name: 'Luxury Gold',
    primary: '#D97706',
    background: '#FFFBEB',
    accent: '#78350F',
    text: '#451A03',
    font: 'Playfair Display',
    rounded: 'rounded-sm',
    buttonStyle: 'outline',
    gradient: false,
    pattern: 'none',
  },
};

export const GOOGLE_FONTS = [
  'Inter',
  'Poppins',
  'Montserrat',
  'Roboto',
  'Playfair Display',
  'Lato',
  'Oswald',
  'Merriweather',
  'Quicksand',
  'Nunito',
  'Raleway',
  'Open Sans',
];
